if(window.location.search===""){actualizarNoticias()}else{const query=obtenerParametro("q");const order=obtenerParametro("order");if(query){document.getElementById("buscador").value=query;document.querySelector('input[name="filtro"]:checked').value=order;buscarNoticias()}}
function obtenerParametro(nombre){const params=new URLSearchParams(window.location.search);return params.get(nombre)};const radios=document.querySelectorAll('input[name="filtro"]');radios.forEach(a=>{a.addEventListener("change",function(){const b=document.querySelector('input[name="filtro"]:checked').value;cargarNoticias(b)})});
async function cargarNoticias(a){try{const b=await fetch(`php/getnoticias_ordenado.php?order=${a}`);if(!b.ok)throw Error(`Error HTTP: ${b.status}`);const c=await b.json();if(c.mensaje)throw Error(c.mensaje);mostrarElementos(c)}catch(b){console.error("Error: ",b),alert("Hubo un error al obtener las noticias.")}}
async function leerNoticiasRSS(){try{if(!esURLValida(document.getElementById("feeds").value.toString()))return alert("No es una URL v\u00e1lida"),!1;await insertarFeed();await insertarSecuencia();const a=document.querySelector('input[name="filtro"]:checked').value;await cargarNoticias(a)}catch(a){console.error("Error:",a),alert("Hubo un error al leer el feed.")}}
async function actualizarNoticias(){try{await insertarSecuencia();const a=document.querySelector('input[name="filtro"]:checked').value;await cargarNoticias(a)}catch(a){console.error("Error:",a),alert("Hubo un error al leer el feed.")}}document.getElementById("buscador").addEventListener("keyup",function(a){"Enter"===a.key&&buscarNoticias()});
async function buscarNoticias(){try{const a=document.getElementById("buscador").value.toString(),b=document.querySelector('input[name="filtro"]:checked').value,c=await fetch("php/buscar_ordenado.php?q="+a+"&order="+b);if(!c.ok)throw Error(`Error HTTP: ${c.status}`);const d=await c.json();if(d.mensaje)throw Error(d.mensaje);mostrarElementos(d)}catch(a){console.error("Error: ",a),alert("Hubo un error al obtener las noticias.")}}
async function insertarFeed(){try{const a={url:document.getElementById("feeds").value.toString()},b=await fetch("php/insertfeed.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(a)});if(!b.ok)throw Error(`Error HTTP: ${b.status}`);const c=await b.json();alert(c.mensaje)}catch(a){console.error("Error: ",a),alert("Hubo un error al insertar el feed.")}}
async function insertarSecuencia(){try{const a=await obtenerFeeds();await insertarNoticias(a)}catch(a){console.error("Error:",a)}}async function obtenerFeeds(){try{const a=await fetch("php/getfeeds.php");if(!a.ok)throw Error(`Error HTTP: ${a.status}`);return await a.json()}catch(a){console.error("Error: ",a),alert("Hubo un error al obtener los feeds.")}}
async function insertarNoticias(a){try{const b={};a.forEach(e=>{b[e.titulo]={url:e.url,rssurl:e.rssurl}});const c=await fetch("php/insertnoticias.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});if(!c.ok)throw Error(`Error HTTP: ${c.status}`);const d=await c.json();alert(d.mensaje)}catch(b){console.error("Error: ",b),alert("Hubo un error al insertar las noticias.")}}
async function obtenerNoticias(){try{const a=await fetch("php/getnoticias.php");if(!a.ok)throw Error(`Error HTTP: ${a.status}`);const b=await a.json();if(b.mensaje)throw Error(b.mensaje);mostrarElementos(b)}catch(a){console.error("Error: ",a),alert("Hubo un error al obtener las noticias.")}}
function mostrarElementos(a){const b=document.getElementById("noticias-container");b.innerHTML="";a.forEach(c=>{const d=c.categorias,e=document.createElement("div"),f=document.createElement("a");f.className="link-noticia";f.href=`${c.urlnoticia}`;const g=document.createElement("div");g.className="card";const h=document.createElement("div");h.className="card-image";h.innerHTML=`<img src="${c.urlimagen}" alt="Imagen" width="400px" height="100px">`;const k=document.createElement("div");k.className="card-content";
k.innerHTML=`<div class="card-title">${c.titulo}</div><div class="card-date">${c.fecha}</div><div class="card-category">Categoria:${d}</div><div class="card-text">${c.descripcion}</div>`;g.appendChild(h);g.appendChild(k);f.appendChild(g);e.appendChild(f);b.innerHTML+=e.innerHTML})}function esURLValida(a){try{return new URL(a),!0}catch(b){return!1}};
